version: '3'
services:
  backend:
    image: mayllon/backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/demo
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 